CREATE TABLE IF NOT EXISTS poll (
    id INT NOT NULL AUTO_INCREMENT,
    body TEXT NOT NULL,
    options TEXT NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    expiresAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

